### ISSUE TITLE
u-boot 2020.10 am335x bootz fixes patch

### ISSUE THREAD

**Issue by acostach** [RobertCNelson/Bootloader-Builder#14]
Hi @RobertCNelson , looking at the u-boot 2020.10 folder I see the patch that adds overlay support and other fixes for am 335x is not present. Do you have any plans to add it or maybe it is available elsewhere? We're looking at updating some fleets with several thousand beaglebone devices and it would be great if we could also update to the latest u-boot. Thank you

**Comment by RobertCNelson** [comment]
Hi @acostach, so the main reason we've 'stalled' am335x onto v2019.04, was the removal of Ethernet support on the legacy 'board' path.  After v2019.04, the only way to have Ethernet in u-boot is to use the "device-tree" path. Another risk with v2019.04+ is the size of MLO, the dtb's end up bloating the size. While we have been shipping a 4MB hold for a while, there was still a time we only had a 1MB hole, which would break those systems.  Since v2019.04 u-boot's been stripping the dtb size, so i belive that not as bad as before.

So that just leaves lots and lots of testing, i think we can now switch back to mainline u-boot. ;)

Regards,

**Comment by acostach** [comment]
I see, thank you Robert!
